/**
 * Demo seed data for Calendar and Drive apps.
 * Gives Luba a realistic feel of the UI with UCW wedding-planning content.
 */
import type { DbCalendarEvent, DbDriveItem } from '@/types/database'

const USER_ID = 'demo-user-001'

// ── Helpers ──

function id(n: number) {
  return `demo-${String(n).padStart(4, '0')}`
}

function iso(month: number, day: number, hour = 0, min = 0) {
  return new Date(2026, month - 1, day, hour, min).toISOString()
}

const now = new Date()
const thisYear = now.getFullYear()
const thisMonth = now.getMonth() // 0-indexed

function isoRel(dayOffset: number, hour = 0, min = 0) {
  const d = new Date(thisYear, thisMonth, now.getDate() + dayOffset, hour, min)
  return d.toISOString()
}

// ── Calendar Events ──

export const DEMO_CALENDAR_EVENTS: DbCalendarEvent[] = [
  // Today
  {
    id: id(1),
    user_id: USER_ID,
    title: 'Final walkthrough — Villa Santa Cruz',
    description: 'Walk venue with Dani. Confirm ceremony arch placement & cocktail flow.',
    start_at: isoRel(0, 10, 0),
    end_at: isoRel(0, 11, 30),
    all_day: false,
    color: '#2a7a94',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-5),
    updated_at: isoRel(-1),
  },
  {
    id: id(2),
    user_id: USER_ID,
    title: 'Sarah & James — Tasting call',
    description: 'Review catering menu with Cocina del Cabo. Couple joins via Zoom.',
    start_at: isoRel(0, 14, 0),
    end_at: isoRel(0, 15, 0),
    all_day: false,
    color: '#3d8b9e',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-3),
    updated_at: isoRel(-1),
  },
  {
    id: id(3),
    user_id: USER_ID,
    title: 'Inventory check — warehouse',
    description: 'Verify linen stock + candle holders for weekend events.',
    start_at: isoRel(0, 16, 30),
    end_at: isoRel(0, 17, 30),
    all_day: false,
    color: '#5b8a65',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-2),
    updated_at: isoRel(-1),
  },

  // Tomorrow
  {
    id: id(4),
    user_id: USER_ID,
    title: 'Emily & Marco — Venue tour',
    description: 'New lead. Showing Sunset Monalisa & Esperanza.',
    start_at: isoRel(1, 9, 0),
    end_at: isoRel(1, 12, 0),
    all_day: false,
    color: '#3d8b9e',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-4),
    updated_at: isoRel(-1),
  },
  {
    id: id(5),
    user_id: USER_ID,
    title: 'Florista meeting — Cabo Flowers',
    description: 'Seasonal availability for August weddings. Bring lookbook samples.',
    start_at: isoRel(1, 14, 0),
    end_at: isoRel(1, 15, 0),
    all_day: false,
    color: '#8a7aaa',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-6),
    updated_at: isoRel(-2),
  },

  // Day after tomorrow
  {
    id: id(6),
    user_id: USER_ID,
    title: 'Rachel & David — Wedding day',
    description: null,
    start_at: isoRel(2, 0, 0),
    end_at: isoRel(2, 23, 59),
    all_day: true,
    color: '#b8883a',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-30),
    updated_at: isoRel(-1),
  },
  {
    id: id(7),
    user_id: USER_ID,
    title: 'Setup crew at Flora Farms — 7 AM',
    description: 'Coordinate table setup, linens, lighting rig.',
    start_at: isoRel(2, 7, 0),
    end_at: isoRel(2, 10, 0),
    all_day: false,
    color: '#b8883a',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-10),
    updated_at: isoRel(-1),
  },
  {
    id: id(8),
    user_id: USER_ID,
    title: 'Hair & Makeup team arrives',
    description: 'Bridal suite. Coordinate with photographer for getting-ready shots.',
    start_at: isoRel(2, 12, 0),
    end_at: isoRel(2, 14, 0),
    all_day: false,
    color: '#b8883a',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-10),
    updated_at: isoRel(-1),
  },
  {
    id: id(9),
    user_id: USER_ID,
    title: 'Ceremony — sunset',
    description: 'Sunset at 6:42 PM. Ceremony starts 30 min before.',
    start_at: isoRel(2, 18, 12),
    end_at: isoRel(2, 18, 45),
    all_day: false,
    color: '#b8883a',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-10),
    updated_at: isoRel(-1),
  },

  // Later this week
  {
    id: id(10),
    user_id: USER_ID,
    title: 'Borja — Lead follow-ups',
    description: 'Review 5 new Instagram leads. Draft initial responses.',
    start_at: isoRel(3, 10, 0),
    end_at: isoRel(3, 11, 0),
    all_day: false,
    color: '#4a9090',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-2),
    updated_at: isoRel(-1),
  },
  {
    id: id(11),
    user_id: USER_ID,
    title: 'DJ soundcheck — Chileno Bay',
    description: 'Test speaker placement for terrace reception.',
    start_at: isoRel(4, 15, 0),
    end_at: isoRel(4, 16, 30),
    all_day: false,
    color: '#5a7fa0',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-7),
    updated_at: isoRel(-1),
  },
  {
    id: id(12),
    user_id: USER_ID,
    title: 'Team meeting — weekly sync',
    description: 'Luba + Dani + Borja. Review upcoming weddings, vendor issues.',
    start_at: isoRel(5, 9, 0),
    end_at: isoRel(5, 10, 0),
    all_day: false,
    color: '#3d8b9e',
    recurrence_rule: 'weekly',
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-30),
    updated_at: isoRel(-1),
  },

  // Next week
  {
    id: id(13),
    user_id: USER_ID,
    title: 'Megan & Alejandro — Proposal review',
    description: 'Present full wedding proposal + quotation. Zoom call.',
    start_at: isoRel(7, 11, 0),
    end_at: isoRel(7, 12, 0),
    all_day: false,
    color: '#3d8b9e',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-3),
    updated_at: isoRel(-1),
  },
  {
    id: id(14),
    user_id: USER_ID,
    title: 'Photographer portfolio review',
    description: 'Compare 3 new photographers for the preferred vendor list.',
    start_at: isoRel(8, 14, 0),
    end_at: isoRel(8, 15, 30),
    all_day: false,
    color: '#9c8b78',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-5),
    updated_at: isoRel(-2),
  },

  // Past events (last few days)
  {
    id: id(15),
    user_id: USER_ID,
    title: 'Natalie & Chris — Final payment received',
    description: null,
    start_at: isoRel(-1, 0, 0),
    end_at: isoRel(-1, 23, 59),
    all_day: true,
    color: '#5b8a65',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-2),
    updated_at: isoRel(-1),
  },
  {
    id: id(16),
    user_id: USER_ID,
    title: 'Dani — Vendor contract renewals',
    description: 'Renewed Cabo Flowers, Cocina del Cabo, DJ Roberto.',
    start_at: isoRel(-2, 10, 0),
    end_at: isoRel(-2, 11, 30),
    all_day: false,
    color: '#4a9090',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-5),
    updated_at: isoRel(-2),
  },
  {
    id: id(17),
    user_id: USER_ID,
    title: 'Lauren & Miguel — Lookbook delivered',
    description: null,
    start_at: isoRel(-3, 16, 0),
    end_at: isoRel(-3, 16, 30),
    all_day: false,
    color: '#8a7aaa',
    recurrence_rule: null,
    google_event_id: null,
    google_calendar_id: null,
    created_at: isoRel(-4),
    updated_at: isoRel(-3),
  },
]

// ── Drive Items ──

const ROOT_FOLDERS: DbDriveItem[] = [
  {
    id: id(100),
    user_id: USER_ID,
    parent_id: null,
    name: 'Weddings 2026',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-60),
    updated_at: isoRel(-1),
  },
  {
    id: id(101),
    user_id: USER_ID,
    parent_id: null,
    name: 'Vendor Contracts',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-90),
    updated_at: isoRel(-5),
  },
  {
    id: id(102),
    user_id: USER_ID,
    parent_id: null,
    name: 'Templates',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-120),
    updated_at: isoRel(-10),
  },
  {
    id: id(103),
    user_id: USER_ID,
    parent_id: null,
    name: 'Marketing',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-45),
    updated_at: isoRel(-3),
  },
  {
    id: id(104),
    user_id: USER_ID,
    parent_id: null,
    name: 'UCW Brand Kit.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 2_400_000,
    storage_path: 'demo/brand-kit.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-90),
    updated_at: isoRel(-30),
  },
  {
    id: id(105),
    user_id: USER_ID,
    parent_id: null,
    name: 'Pricing Guide 2026.xlsx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size_bytes: 185_000,
    storage_path: 'demo/pricing-2026.xlsx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-20),
    updated_at: isoRel(-2),
  },
  {
    id: id(106),
    user_id: USER_ID,
    parent_id: null,
    name: 'Insurance Certificate.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 540_000,
    storage_path: 'demo/insurance.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-60),
    updated_at: isoRel(-60),
  },
]

// Weddings 2026 subfolder contents
const WEDDINGS_CHILDREN: DbDriveItem[] = [
  {
    id: id(110),
    user_id: USER_ID,
    parent_id: id(100),
    name: 'Rachel & David — Jun 5',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-40),
    updated_at: isoRel(-1),
  },
  {
    id: id(111),
    user_id: USER_ID,
    parent_id: id(100),
    name: 'Sarah & James — Jul 19',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-30),
    updated_at: isoRel(-2),
  },
  {
    id: id(112),
    user_id: USER_ID,
    parent_id: id(100),
    name: 'Emily & Marco — Aug 23',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-15),
    updated_at: isoRel(-1),
  },
  {
    id: id(113),
    user_id: USER_ID,
    parent_id: id(100),
    name: 'Megan & Alejandro — Sep 12',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-10),
    updated_at: isoRel(-1),
  },
  {
    id: id(114),
    user_id: USER_ID,
    parent_id: id(100),
    name: 'Natalie & Chris — Oct 4',
    type: 'folder',
    mime_type: null,
    size_bytes: null,
    storage_path: null,
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-20),
    updated_at: isoRel(-1),
  },
]

// Rachel & David subfolder contents
const RACHEL_DAVID_FILES: DbDriveItem[] = [
  {
    id: id(120),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Timeline — Rachel & David.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 320_000,
    storage_path: 'demo/rachel-timeline.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-10),
    updated_at: isoRel(-1),
  },
  {
    id: id(121),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Lookbook — Rachel & David.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 8_500_000,
    storage_path: 'demo/rachel-lookbook.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-8),
    updated_at: isoRel(-2),
  },
  {
    id: id(122),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Quotation Final.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 210_000,
    storage_path: 'demo/rachel-quote.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-15),
    updated_at: isoRel(-5),
  },
  {
    id: id(123),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Seating Chart v3.xlsx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size_bytes: 48_000,
    storage_path: 'demo/rachel-seating.xlsx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-5),
    updated_at: isoRel(-1),
  },
  {
    id: id(124),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Inspiration Board.jpg',
    type: 'file',
    mime_type: 'image/jpeg',
    size_bytes: 3_200_000,
    storage_path: 'demo/rachel-inspo.jpg',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-35),
    updated_at: isoRel(-35),
  },
  {
    id: id(125),
    user_id: USER_ID,
    parent_id: id(110),
    name: 'Vendor Contact List.docx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size_bytes: 67_000,
    storage_path: 'demo/rachel-vendors.docx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-20),
    updated_at: isoRel(-3),
  },
]

// Vendor Contracts subfolder contents
const VENDOR_FILES: DbDriveItem[] = [
  {
    id: id(130),
    user_id: USER_ID,
    parent_id: id(101),
    name: 'Cabo Flowers — 2026 Agreement.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 410_000,
    storage_path: 'demo/contract-flowers.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-45),
    updated_at: isoRel(-2),
  },
  {
    id: id(131),
    user_id: USER_ID,
    parent_id: id(101),
    name: 'Cocina del Cabo — Catering.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 380_000,
    storage_path: 'demo/contract-catering.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-50),
    updated_at: isoRel(-5),
  },
  {
    id: id(132),
    user_id: USER_ID,
    parent_id: id(101),
    name: 'DJ Roberto — Music & Sound.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 290_000,
    storage_path: 'demo/contract-dj.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-55),
    updated_at: isoRel(-2),
  },
  {
    id: id(133),
    user_id: USER_ID,
    parent_id: id(101),
    name: 'Photo Studio Baja — 2026.pdf',
    type: 'file',
    mime_type: 'application/pdf',
    size_bytes: 510_000,
    storage_path: 'demo/contract-photo.pdf',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-40),
    updated_at: isoRel(-10),
  },
]

// Templates subfolder contents
const TEMPLATE_FILES: DbDriveItem[] = [
  {
    id: id(140),
    user_id: USER_ID,
    parent_id: id(102),
    name: 'Timeline Template.docx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size_bytes: 95_000,
    storage_path: 'demo/tmpl-timeline.docx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-120),
    updated_at: isoRel(-30),
  },
  {
    id: id(141),
    user_id: USER_ID,
    parent_id: id(102),
    name: 'Lookbook Template.pptx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size_bytes: 4_200_000,
    storage_path: 'demo/tmpl-lookbook.pptx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-120),
    updated_at: isoRel(-20),
  },
  {
    id: id(142),
    user_id: USER_ID,
    parent_id: id(102),
    name: 'Quotation Template.xlsx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size_bytes: 78_000,
    storage_path: 'demo/tmpl-quote.xlsx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-120),
    updated_at: isoRel(-15),
  },
  {
    id: id(143),
    user_id: USER_ID,
    parent_id: id(102),
    name: 'Email — Welcome New Lead.txt',
    type: 'file',
    mime_type: 'text/plain',
    size_bytes: 3_200,
    storage_path: 'demo/tmpl-email-welcome.txt',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-100),
    updated_at: isoRel(-10),
  },
  {
    id: id(144),
    user_id: USER_ID,
    parent_id: id(102),
    name: 'Email — Payment Reminder.txt',
    type: 'file',
    mime_type: 'text/plain',
    size_bytes: 2_800,
    storage_path: 'demo/tmpl-email-payment.txt',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-100),
    updated_at: isoRel(-10),
  },
]

// Marketing subfolder contents
const MARKETING_FILES: DbDriveItem[] = [
  {
    id: id(150),
    user_id: USER_ID,
    parent_id: id(103),
    name: 'Instagram Reel — Beach Setup.mp4',
    type: 'file',
    mime_type: 'video/mp4',
    size_bytes: 45_000_000,
    storage_path: 'demo/reel-beach.mp4',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-10),
    updated_at: isoRel(-3),
  },
  {
    id: id(151),
    user_id: USER_ID,
    parent_id: id(103),
    name: 'UCW Logo White.png',
    type: 'file',
    mime_type: 'image/png',
    size_bytes: 125_000,
    storage_path: 'demo/logo-white.png',
    public_url: null,
    is_published: true,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-90),
    updated_at: isoRel(-30),
  },
  {
    id: id(152),
    user_id: USER_ID,
    parent_id: id(103),
    name: 'Testimonial — Sarah & James.docx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size_bytes: 28_000,
    storage_path: 'demo/testimonial-sarah.docx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-7),
    updated_at: isoRel(-2),
  },
  {
    id: id(153),
    user_id: USER_ID,
    parent_id: id(103),
    name: 'Social Media Calendar Q2.xlsx',
    type: 'file',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size_bytes: 92_000,
    storage_path: 'demo/social-q2.xlsx',
    public_url: null,
    is_published: false,
    google_file_id: null,
    metadata: {},
    created_at: isoRel(-25),
    updated_at: isoRel(-5),
  },
]

// All drive items in a flat list, indexed by parent_id
const ALL_DRIVE_ITEMS: DbDriveItem[] = [
  ...ROOT_FOLDERS,
  ...WEDDINGS_CHILDREN,
  ...RACHEL_DAVID_FILES,
  ...VENDOR_FILES,
  ...TEMPLATE_FILES,
  ...MARKETING_FILES,
]

export function getDemoDriveItems(parentId: string | null): DbDriveItem[] {
  return ALL_DRIVE_ITEMS
    .filter((item) => item.parent_id === parentId)
    .sort((a, b) => {
      // Folders first, then by name
      if (a.type !== b.type) return a.type === 'folder' ? -1 : 1
      return a.name.localeCompare(b.name)
    })
}

export function getDemoDriveItem(id: string): DbDriveItem | undefined {
  return ALL_DRIVE_ITEMS.find((item) => item.id === id)
}

export function getDemoDriveFolderPath(folderId: string | null): DbDriveItem[] {
  if (!folderId) return []
  const path: DbDriveItem[] = []
  let currentId: string | null = folderId
  while (currentId) {
    const item = ALL_DRIVE_ITEMS.find((i) => i.id === currentId)
    if (!item) break
    path.unshift(item)
    currentId = item.parent_id
  }
  return path
}
